spring.application.name=ddeonabom
spring.devtools.restart.enabled=true

#oracle 연결 (url 표준 키값으로 세팅)
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}


#타임리프 설정
spring.thymeleaf.cache=false

#mybatis
#파일 만들면 주석 풀기
mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=kh.ddeonabom.*.model.vo, kh.ddeonabom.*.*.model.vo
mybatis.configuration.jdbc-type-for-null=null

#g메일
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saundayy@gmail.com
spring.mail.password=wexk jsvn tbwc spyr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 🔒 이 줄이 있어야 내 컴퓨터의 local 파일이 위 환경 변수들을 씹고 덮어씁니다!
spring.config.import=optional:application-local.properties